### ISSUE TITLE
Possible bug in default join `type` condition logic when `type` or `table` is omitted?

### ISSUE THREAD

**Issue by thadguidry** [kdhrubo/db2rest-web#24]
@Dhrubo Looks like if we omit `type` attribute from the `/_expand` data then also omit `table` attribute, then it's a self join?  But your Self Join example and also the key attributes table listing Description showing the **Default value: "INNER"** seems to conflict with the actual default value of `type` if its omitted?

Seems we need to fix the documentation, but first, we need to know:
1. What is the join type assumed (default) if `table` and `type` are omitted and only `fields` and `on` are used with `/film/_expand` ?
2. What is the join type assumed (default) if `table` is present and only `fields` and `on` are used with `/film/_expand` ?
3. Or do we throw an error on logic in scenario 1. or 2. because it's not allowed and we need to fix documentation for Joining?

**Comment by kdhrubo** [comment]
closing this the type is now `joinType`
