### ISSUE TITLE
Document INCLUDED_SCHEMA

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest-web#75]

**Comment by thadguidry** [comment]
It's currently here:
https://github.com/9tigerio/db2rest-web/blob/master/docs/read/restrict-schemas.mdx

But maybe that content from that page should be moved under someplace else?
Like: 
https://github.com/9tigerio/db2rest-web/blob/master/docs/configuration-parameters.md

What do you think?

**Comment by kdhrubo** [comment]
The parameter should be in the list
There is a maven plugin that automatically collects all parameters in
spring boot app and documents them. Need to check that

**Comment by kdhrubo** [comment]
Added to parameter list
